{% set version = '1.5.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsyncrosim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/syncrosim/rsyncrosim/releases/download/{{ version }}/rsyncrosim_{{ version }}.tar.gz
    - https://github.com/syncrosim/rsyncrosim/archive/v{{ version }}.tar.gz
  sha256: 7ab1ec803bc1e41e6d2241b33614d29b975de0f242b20c13fc7defd21a3a4b2f

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-gtools
    - r-lifecycle
    - r-terra

  run:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-gtools
    - r-lifecycle
    - r-terra

test:
  commands:
    - $R -e "library('rsyncrosim')"           # [not win]
    - "\"%R%\" -e \"library('rsyncrosim')\""  # [win]

about:
  home: https://syncrosim.github.io/rsyncrosim/
  license: MIT
  summary: '''SyncroSim'' is a generalized framework for managing scenario-based datasets (<https://syncrosim.com/>).
    ''rsyncrosim'' provides an interface to ''SyncroSim''. Simulation models can be
    added to ''SyncroSim'' in order to transform these datasets, taking advantage of
    general features such as defining scenarios of model inputs, running Monte Carlo
    simulations, and summarizing model outputs. ''rsyncrosim'' requires ''SyncroSim''
    2.4.44 or higher (API documentation: <https://docs.syncrosim.com/>).'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - katieb1
  