{% set version = '1.4.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsyncrosim
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/syncrosim/rsyncrosim
  git_tag: 1.4.8

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-gtools
    - r-lifecycle
    - r-terra

  run:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-gtools
    - r-lifecycle
    - r-terra

test:
  commands:
    - $R -e "library('rsyncrosim')"           # [not win]
    - "\"%R%\" -e \"library('rsyncrosim')\""  # [win]

about:
  home: <https://syncrosim.github.io/rsyncrosim/>
  license: MIT
  summary: '''SyncroSim'' is a generalized framework for managing scenario-based datasets (<https://syncrosim.com/>).
    ''rsyncrosim'' provides an interface to ''SyncroSim''. Simulation models can be
    added to ''SyncroSim'' in order to transform these datasets, taking advantage of
    general features such as defining scenarios of model inputs, running Monte Carlo
    simulations, and summarizing model outputs. ''rsyncrosim'' requires ''SyncroSim''
    2.3.5 or higher (API documentation: <https://docs.syncrosim.com/>).'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - katieb1

# The original CRAN metadata for this package was:

# Package: rsyncrosim
# Type: Package
# Title: The R Interface to 'SyncroSim'
# Version: 1.4.8
# Authors@R: c( person("Colin", "Daniel", email = "colin.daniel@apexrms.com", role = c("aut", "cre")), person("Josie", "Hughes", email = "josie.hughes@canada.ca", role = "aut"), person("Valentin", "Lucet", role = "aut"), person("Alex", "Embrey", role = "aut"), person("Katie", "Birchard", role = "aut"), person("Leonardo", "Frid", role = "aut"), person("Tabitha", "Kennedy", role = "aut"), person("Shreeram", "Senthivasan", role = "aut"), person("ApexRMS", role="cph"))
# Description: 'SyncroSim' is a generalized framework for managing scenario-based datasets (<https://syncrosim.com/>). 'rsyncrosim' provides an interface to 'SyncroSim'. Simulation models can be added to 'SyncroSim' in order to transform these datasets, taking advantage of general features such as defining scenarios of model inputs, running Monte Carlo simulations, and summarizing model outputs. 'rsyncrosim' requires 'SyncroSim' 2.3.5 or higher (API documentation: <https://docs.syncrosim.com/>).
# License: MIT + file LICENSE
# Encoding: UTF-8
# Imports: methods, DBI, RSQLite, terra, gtools, lifecycle
# Suggests: knitr, testthat (>= 3.0.0), ggplot2, Rcpp, rmarkdown
# SystemRequirements: SyncroSim (>=2.3.10)
# Collate: 'AAAClassDefinitions.R' 'addPackage.R' 'addRow.R' 'addon.R' 'autogentags.R' 'backup.R' 'breakpoint.R' 'command.R' 'condaFilepath.R' 'datasheet.R' 'datasheetRaster.R' 'datasheetSpatRaster.R' 'dateModified.R' 'delete.R' 'dependency.R' 'deprecated.R' 'description.R' 'disableAddon.R' 'enableAddon.R' 'filepath.R' 'folder.R' 'folderId.R' 'ignoreDependencies.R' 'info.R' 'installConda.R' 'internalHelpers.R' 'name.R' 'scenarioId.R' 'projectId.R' 'sqlStatement.R' 'scenario.R' 'project.R' 'ssimLibrary.R' 'session.R' 'internalWrappers.R' 'mergeDependencies.R' 'owner.R' 'package.R' 'parentId.R' 'print.R' 'printCmd.R' 'published.R' 'readOnly.R' 'removePackage.R' 'rsyncrosim.R' 'run.R' 'runLog.R' 'saveDatasheet.R' 'silent.R' 'ssimEnvironment.R' 'ssimUpdate.R' 'updatePackage.R' 'useConda.R' 'version.R'
# RoxygenNote: 7.2.3
# URL: <https://syncrosim.github.io/rsyncrosim/>
# BugReports: https://github.com/syncrosim/rsyncrosim/issues/
# Config/testthat/edition: 3
# Roxygen: list(markdown = TRUE)
